/* gallery-data.js - tools/build-gallery.ps1 tarafindan uretilir.
   Yeni gorsel ekledikten sonra tekrar calistirin:
   powershell -ExecutionPolicy Bypass -File tools\build-gallery.ps1 */
window.GALLERY_FILES = [
  'adfe.png',
  'Adsırgrz tasarım.png',
  'Adsıwerwz tasarım.png',
  'Adsız regtasarım.png',
  'Adsız tafrfrsarım.png',
  'Adsız tafrfsarım.png',
  'Adsız tarfregsarım.png',
  'Adsız tasacvfrım.png',
  'Adsız tasadfsrım.png',
  'Adsız tasaefrrım.png',
  'Adsız tasareerrım.png',
  'Adsız tasaregerrım.png',
  'Adsız tasarerım.png',
  'Adsız tasarg5etım.png',
  'Adsız tasargfhtım.png',
  'Adsız tasargrerım.png',
  'Adsız tasarım.png',
  'Adsız tasartgeım.png',
  'Adsız tasartwrım.png',
  'Adsız tasasfrım.png',
  'Adsız tasatg5erım.png',
  'Adsız taswrfarım.png',
  'Adsız tathtrsarım.png',
  'Adsız tatyrtsarım.png',
  'Adsız tdfsasarım.png',
  'Adsız tgetasarım.png',
  'Adsız tgregegasarım.png',
  'asdjfsf.png',
  'bdfgdgr.png',
  'ddcscds.png',
  'ddsc.png',
  'dfdes.png',
  'dfggtdg.png',
  'dfghjklşlt.png',
  'dfkkfewkpo.png',
  'dfrjıfgjeıfe.png',
  'dfs.png',
  'dfsekf.png',
  'dgthtd.png',
  'djsfıjgerıjgktea.png',
  'dkfgokreoger.png',
  'dlfskf.png',
  'dmznfn.png',
  'dncsd.png',
  'dsf.png',
  'dsfd.png',
  'dsfdg.png',
  'dsfds.png',
  'dsfdsfl.png',
  'dsfdskf.png',
  'dsfes.png',
  'dsfesfe.png',
  'dsfsd.png',
  'dsfsf.png',
  'dsfsrf.png',
  'dsgfdg.png',
  'dsgffg.png',
  'dskjgjegjrwfw.png',
  'earfergegf.png',
  'efjergre.png',
  'ejjfıeje.png',
  'ergjtgdtgeths.png',
  'erıgjpeowkf.png',
  'eryutryffoosae.png',
  'ewrkoetkht.png',
  'ewujfuerg.png',
  'fdgd.png',
  'fdgdfg.png',
  'fdgfhdyf.png',
  'fdgfhyjut.png',
  'fdgoktrhkpot.png',
  'fgklfdmgl.png',
  'fgrd.png',
  'fgre.png',
  'fgsthyhj.png',
  'fgyrhhtgr.png',
  'fır9er0gote.png',
  'fkggdgkr.png',
  'fkgopktopgker.png',
  'fnsejfıewı.png',
  'fsfrgf.png',
  'fskkrsjgrg.png',
  'gfgtrjkuoı.png',
  'ghbrhf.png',
  'ghryry.png',
  'ghtge.png',
  'ghyyf.png',
  'gırjfrfewfe.png',
  'gjnerfw3rfes.png',
  'gkoteoget.png',
  'greggrfaefae.png',
  'gtg.png',
  'gtsrhtyjun.png',
  'hntyjuyu.png',
  'ıjfıewf.png',
  'jgıojerıt.png',
  'jsıfvjsfjws.png',
  'kfrejgjegw.png',
  'ksfkgergfwef.png',
  'kvdjfea.png',
  'ldvd.png',
  'oerfıgoetgo.png',
  'ookgoergo4we.png',
  'pfı4wrjgıjer.png',
  'reegtrhryg.png',
  'rejgetjgoıjteg.png',
  'rfgerg.png',
  'rfjgırfewkfw.png',
  'rforegoetr.png',
  'rgftghtrht.png',
  'rgıergı4wırw.png',
  'rgketrgke.png',
  'rgtry.png',
  'rıgıptegpe.png',
  'rjfgerjgre.png',
  'rokırejgjerge.png',
  'rtgrgerdged.png',
  'rtgtrh.png',
  'sddffgskg.png',
  'sdfghjk.png',
  'sdjfjsgfjs.png',
  'sfgdg.png',
  'sfgjfj.png',
  'sfgjıdg.png',
  'sfkvrkgre.png',
  'sfregrtd.png',
  'sfregtegtrf.png',
  'sfreıgjtjgts.png',
  'sfrf.png',
  'soğkgor.png',
  'tgtryt.png',
  'trhjuj86ı7t.png',
  'ufhvuerhfew.png',
  'vff.png',
  'vfrsv.png',
  'zcsd.png',
  'zdfs.png'
];
