/* gallery-data.js - tools/build-gallery.ps1 tarafindan uretilir.
   Yeni gorsel ekledikten sonra tekrar calistirin:
   powershell -ExecutionPolicy Bypass -File tools\build-gallery.ps1 */
window.GALLERY_FILES = [
  'adfe.png',
  'ADIFJFJSFSE.png',
  'ADJFSSVS.png',
  'Adsırgrz tasarım.png',
  'Adsıwerwz tasarım.png',
  'Adsız regtasarım.png',
  'Adsız tafrfrsarım.png',
  'Adsız tafrfsarım.png',
  'Adsız tarfregsarım.png',
  'Adsız tasacvfrım.png',
  'Adsız tasadfsrım.png',
  'Adsız tasaefrrım.png',
  'Adsız tasareerrım.png',
  'Adsız tasaregerrım.png',
  'Adsız tasarerım.png',
  'Adsız tasarg5etım.png',
  'Adsız tasargfhtım.png',
  'Adsız tasargrerım.png',
  'Adsız tasarım.png',
  'Adsız tasarım.pngRJGIERFW.png',
  'Adsız tasarım.pngSFJGERGER.png',
  'Adsız tasartgeım.png',
  'Adsız tasartwrım.png',
  'Adsız tasasfrım.png',
  'Adsız tasatg5erım.png',
  'Adsız taswrfarım.png',
  'Adsız tathtrsarım.png',
  'Adsız tatyrtsarım.png',
  'Adsız tdfsasarım.png',
  'Adsız tgetasarım.png',
  'Adsız tgregegasarım.png',
  'AEFJJFEWS.png',
  'asdjfsf.png',
  'bdfgdgr.png',
  'CDSKKVSFJVS.png',
  'ddcscds.png',
  'ddsc.png',
  'dfdes.png',
  'dfggtdg.png',
  'dfghjklşlt.png',
  'dfkkfewkpo.png',
  'dfrjıfgjeıfe.png',
  'dfs.png',
  'dfsekf.png',
  'dgthtd.png',
  'djsfıjgerıjgktea.png',
  'dkfgokreoger.png',
  'DKFSFESFC.png',
  'DKJVSFJVOS.png',
  'DKSVJFJVS.png',
  'DKVFVPRS.png',
  'DKVKSFVKS.png',
  'dlfskf.png',
  'dmznfn.png',
  'dncsd.png',
  'dsf.png',
  'dsfd.png',
  'dsfdg.png',
  'dsfds.png',
  'dsfdsfl.png',
  'dsfdskf.png',
  'dsfes.png',
  'dsfesfe.png',
  'DSFORKG.png',
  'dsfsd.png',
  'dsfsf.png',
  'dsfsrf.png',
  'dsgfdg.png',
  'dsgffg.png',
  'DSKFVV.png',
  'dskjgjegjrwfw.png',
  'DSKJVKVKS.png',
  'DSKVFKDVKSD.png',
  'DSLVKFJVKER.png',
  'DSVJIFJIVJSV.png',
  'earfergegf.png',
  'efjergre.png',
  'efjırejfı4w,.png',
  'EFJRIJFREFE.png',
  'efkrejjrg.png',
  'ejjfıeje.png',
  'ergjtgdtgeths.png',
  'erıgjpeowkf.png',
  'eryutryffoosae.png',
  'ESFKVKCEA.png',
  'ewrkoetkht.png',
  'ewujfuerg.png',
  'fdgd.png',
  'fdgdfg.png',
  'fdgfhdyf.png',
  'fdgfhyjut.png',
  'FDGHH.png',
  'fdgoktrhkpot.png',
  'FDLKBLDKLVD.png',
  'FDMVKMKV.png',
  'fgklfdmgl.png',
  'fgrd.png',
  'fgre.png',
  'FGRIJGIERGR.png',
  'fgsthyhj.png',
  'fgyrhhtgr.png',
  'FHJRHWEF.png',
  'fhujgkorss.png',
  'fır9er0gote.png',
  'FJRFGRGRW.png',
  'fkggdgkr.png',
  'fkgopktopgker.png',
  'FKKFKKFGS.png',
  'fnsejfıewı.png',
  'fsfrgf.png',
  'fskkrsjgrg.png',
  'FVKLKSLDVS.png',
  'gfgtrjkuoı.png',
  'ghbrhf.png',
  'ghryry.png',
  'ghtge.png',
  'ghyyf.png',
  'GIJRIGJRS.png',
  'gırjfrfewfe.png',
  'GJIJROIFG.png',
  'gjnerfw3rfes.png',
  'gkoteoget.png',
  'greggrfaefae.png',
  'gtg.png',
  'gtsrhtyjun.png',
  'hntyjuyu.png',
  'ıjfıewf.png',
  'ISFJFSGRSFE.png',
  'JFRWOFRW.png',
  'jgıojerıt.png',
  'jsıfvjsfjws.png',
  'KAJIOSJVS.png',
  'KFJFIJGWRS.png',
  'kfrejgjegw.png',
  'KFSVFDVKDF.png',
  'KGJIWERJFIWE.png',
  'KGREKGE.png',
  'KSFKEGKEWR.png',
  'ksfkgergfwef.png',
  'kvdjfea.png',
  'LBOGKDOKBD.png',
  'LDKFKFEW.png',
  'ldvd.png',
  'LFVLFDLBÖDLG.png',
  'oerfıgoetgo.png',
  'ookgoergo4we.png',
  'pfı4wrjgıjer.png',
  'reegtrhryg.png',
  'rejgetjgoıjteg.png',
  'rfgerg.png',
  'rfjgırfewkfw.png',
  'rforegoetr.png',
  'RGERIGWRG.png',
  'rgftghtrht.png',
  'rgıergı4wırw.png',
  'rgketrgke.png',
  'RGTGTR.png',
  'rgtry.png',
  'rıgıptegpe.png',
  'rıwjfrjıgr.png',
  'rjfgerjgre.png',
  'rkreıgjeıg.png',
  'rokırejgjerge.png',
  'rtgrgerdged.png',
  'rtgtrh.png',
  'sddffgskg.png',
  'sdfghjk.png',
  'SDFIRJGR.png',
  'SDFJIRJGRE.png',
  'SDFJIRJGRGR.png',
  'sdjfjsgfjs.png',
  'SDJVFJKVF.png',
  'SDKFJKJGS.png',
  'SDKFVOFKVD.png',
  'SDKVFKFVK.png',
  'SDOKFVJDRFS.png',
  'SDOKVOKO.png',
  'SDVJKRJKFR.png',
  'sfgdg.png',
  'sfgjfj.png',
  'sfgjıdg.png',
  'SFKVFKBDB.png',
  'sfkvrkgre.png',
  'SFOKVOVKD.png',
  'sfregrtd.png',
  'sfregtegtrf.png',
  'sfreıgjtjgts.png',
  'sfrf.png',
  'SFRKRKGFR.png',
  'sfvfsvslj.png',
  'SFVKJFKJE.png',
  'SIFJREJGER.png',
  'SIJGIGJEIGW.png',
  'SKFJKJGKE.png',
  'SKFKFJKGG.png',
  'SKJFGRJGRW.png',
  'SKVFKVKSS.png',
  'SLKVLDKBD.png',
  'SMGVSFVF.png',
  'SOFGKOETKGE.png',
  'SOFKGREGER.png',
  'soğkgor.png',
  'tgtryt.png',
  'trhjuj86ı7t.png',
  'ufhvuerhfew.png',
  'vff.png',
  'vfrsv.png',
  'VKDSJVKJSF.png',
  'WFIGRJEG.png',
  'zcsd.png',
  'zdfs.png'
];
